using Phnx.Security.Algorithms;
using System;

namespace Phnx.Security.Passwords
{
    /// <summary>
    /// A hash generator with a version of zero. Uses <see cref="Pbkdf2Hash"/> with 1024 iterations
    /// </summary>
    public sealed class PasswordHashDefault : IPasswordHash
    {
        /// <summary>
        /// The length of the hash produced by this algorithm
        /// </summary>
        public int HashBytesLength => 128;

        /// <summary>
        /// The length of the salt needed/ generated by this algorithm
        /// </summary>
        public int SaltBytesLength => 24;

        private readonly Pbkdf2Hash _hashGenerator;

        /// <summary>
        /// Create a new instance of <see cref="PasswordHashDefault"/>
        /// </summary>
        public PasswordHashDefault(Pbkdf2Hash hashGenerator)
        {
            _hashGenerator = hashGenerator;
        }

        /// <summary>
        /// Generate a hash from a password and salt
        /// </summary>
        /// <param name="password">The password to hash</param>
        /// <param name="salt">The salt to use</param>
        /// <returns></returns>
        public byte[] GenerateHash(byte[] password, byte[] salt)
        {
            if (password is null)
            {
                throw new ArgumentNullException(nameof(password));
            }
            if (salt is null)
            {
                throw new ArgumentNullException(nameof(salt));
            }

            return _hashGenerator.Hash(password, salt, 1024);
        }

        /// <summary>
        /// Generate a random salt
        /// </summary>
        /// <returns></returns>
        public byte[] GenerateSalt()
        {
            return _hashGenerator.GenerateSalt();
        }
    }
}
