using MarkSFrancis.Security.Passwords.Interface;

namespace MarkSFrancis.Security.Passwords
{
    /// <summary>
    /// A hash generator with a version of zero
    /// </summary>
    public sealed class PasswordHashVersionZero : IPasswordHashVersion
    {
        /// <summary>
        /// The version of this hashing algorithm
        /// </summary>
        public int Version => 0;
        
        /// <summary>
        /// The length of the hash produced by this algorithm
        /// </summary>
        public int HashBytesLength => 128;
        
        /// <summary>
        /// The length of the salt needed/ generated by this algorithm
        /// </summary>
        public int SaltBytesLength => 24;

        /// <summary>
        /// The number of times this hash is ran on any passwords
        /// </summary>
        public int IterationCount => HashGenerator.IterationCount;

        private Pbkdf2Hash HashGenerator { get; }

        /// <summary>
        /// Create a new instance of <see cref="PasswordHashVersionZero"/>
        /// </summary>
        public PasswordHashVersionZero()
        {
            HashGenerator = new Pbkdf2Hash();
        }

        /// <summary>
        /// Generate a hash from a password and salt
        /// </summary>
        /// <param name="password">The password to hash</param>
        /// <param name="salt">The salt to use</param>
        /// <returns></returns>
        public byte[] GenerateHash(byte[] password, byte[] salt)
        {
            return HashGenerator.Hash(password, salt);
        }

        /// <summary>
        /// Generate a random salt
        /// </summary>
        /// <returns></returns>
        public byte[] GenerateSalt()
        {
            return HashGenerator.GenerateSalt();
        }
    }
}